# =========================
# BACKEND
# =========================

backend.jar.path=backend.jar

# =========================
# CLIENT
# =========================

client.jar.path=client.jar

# =========================
# BACKUP
# =========================

backup.folder=backup

# =========================
# DATABASE
# =========================

db.name=store_manager_db

db.username=root

db.password=

# =========================
# MYSQL
# =========================

mysql.path=/opt/homebrew/bin/mysql

mysqldump.path=/opt/homebrew/bin/mysqldump

# =========================
# TECHNICAL
# =========================

technical.password.hash=$2a$10$5W8CtwIj5uS0FgYw.qokiu13BV759dLj7eQ4rMM2eEpDVrs2wMZRy