info:
  name: set-salary-config
  type: http
  seq: 1

http:
  method: POST
  url: http://localhost:8080/api/payroll/config
  body:
    type: json
    data: |-
      {
        "userId": 2,
        "hourlyRate": 30000,
        "overtimeRate": 45000,
        "bonusAmount": 500000,
        "deductionAmount": 100000
      }
  auth:
    type: bearer
    token: 4b2c5627-16e3-4a0c-8c07-b33167ef7958

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
