backend.jar.path=backend.jar

db.name=store_manager_db

db.username=root

db.password=

mysqldump.path=/opt/homebrew/bin/mysqldump

backup.folder=backup

mysql.path=/opt/homebrew/bin/mysql

technical.password.hash=